import fs from 'fs';

// 1. Read package.json
const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8'));

// 2. Manual Version Bump (Split 1.1.21 into [1, 1, 21])
const parts = pkg.version.split('.');
parts[2] = parseInt(parts[2]) + 1; // Increment the last number
const newVersion = parts.join('.');

// 3. Update the package.json file on disk
pkg.version = newVersion;

if (newVersion && pkg.name === 'v-secaccts') {
  fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
} else {
  console.error('Safety check failed: package.json not updated.');
  process.exit(1); // <--- THIS terminates the script and stops the build/deploy
}

// 4. Create the build date
const buildDate = new Date().toLocaleString('en-US', {
  month: 'short',
  day: 'numeric',
  year: 'numeric',
  hour: '2-digit',
  minute: '2-digit',
  // Explicitly omitting 'second' removes the :ss
});

// 5. Write to your source folder for Vue
const content = `// Auto-generated by version-gen.js
export const VERSION = "${newVersion}";
export const BUILD_DATE = "${buildDate}";
`;

fs.writeFileSync('src/services/version-info.js', content);
console.log(`✅ Version Synced: v${newVersion} | ${buildDate}`);
